# Generated by Django 5.2.6 on 2025-09-28 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_kg_per_ha', models.FloatField(blank=True, null=True)),
                ('p_kg_per_ha', models.FloatField(blank=True, null=True)),
                ('k_kg_per_ha', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient', to='agrigeo.crop')),
            ],
        ),
    ]
