# Generated by Django 5.2.6 on 2025-09-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0002_crop_cropnutrient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='slug',
        ),
        migrations.AddField(
            model_name='crop',
            name='k_kg_per_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='n_kg_per_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='p_kg_per_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CropNutrient',
        ),
    ]
