# Generated by Django 5.2.6 on 2025-10-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0003_remove_crop_slug_crop_k_kg_per_ha_crop_n_kg_per_ha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('n_percent', models.FloatField(default=0)),
                ('p_percent', models.FloatField(default=0)),
                ('k_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerStageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('Planting', 'Planting'), ('Top Dressing 1', 'Top Dressing 1'), ('Top Dressing 2', 'Top Dressing 2')], max_length=20)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrigeo.fertilizer')),
            ],
            options={
                'unique_together': {('stage_name', 'fertilizer')},
            },
        ),
    ]
