# Generated by Django 5.2.6 on 2025-10-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0004_fertilizer_fertilizerstagemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_applications', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrigeo.crop')),
            ],
        ),
    ]
