# Generated by Django 5.2.6 on 2025-10-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0005_cropapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropapplication',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
