# Generated by Django 5.2.6 on 2025-10-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0007_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
