# Generated by Django 5.2.6 on 2025-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0008_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmboundary',
            name='area',
            field=models.FloatField(default=0.0, help_text='Calculated area in acres.'),
        ),
        migrations.AddField(
            model_name='farmboundary',
            name='location',
            field=models.CharField(blank=True, help_text='Search location/address provided by the user.', max_length=255),
        ),
    ]
