# Generated by Django 5.2.6 on 2025-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0009_farmboundary_area_farmboundary_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Acric Ferralsols', max_length=100, unique=True)),
                ('summary', models.TextField(help_text='A brief agronomic summary of this soil type.')),
                ('pdf_report', models.FileField(blank=True, help_text='Upload the detailed PDF report here.', null=True, upload_to='soil_reports/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='soil_images/')),
            ],
            options={
                'verbose_name_plural': 'Soil Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('causal_agent', models.CharField(help_text='e.g., Fungal, Bacterial, Viral', max_length=100)),
                ('symptoms', models.TextField(help_text='Visual signs of disease')),
                ('treatment', models.TextField(help_text='Fungicides or cultural practices')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('affected_crops', models.ManyToManyField(related_name='diseases', to='agrigeo.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.TextField(help_text='Visual signs of infestation')),
                ('control_methods', models.TextField(help_text='Chemical or biological control methods')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pests/')),
                ('affected_crops', models.ManyToManyField(related_name='pests', to='agrigeo.crop')),
            ],
        ),
    ]
