# Generated by Django 5.2.6 on 2025-12-07 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0010_soiltaxonomy_disease_pest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='affected_crops',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='affected_crops',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default='No description available', help_text='General description of the disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pest',
            name='description',
            field=models.TextField(default=2, help_text='General description of the pest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(help_text='General treatment options'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='control_methods',
            field=models.TextField(help_text='General control methods'),
        ),
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_symptoms', models.TextField(help_text='Symptoms specific to this crop')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_diseases', to='agrigeo.crop')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_occurrences', to='agrigeo.disease')),
            ],
            options={
                'verbose_name': 'Disease affecting Crop',
                'unique_together': {('crop', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='CropPest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_symptoms', models.TextField(help_text='How does this pest specifically damage this crop?')),
                ('economic_threshold', models.CharField(blank=True, help_text='When should the farmer take action?', max_length=255)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_pests', to='agrigeo.crop')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_occurrences', to='agrigeo.pest')),
            ],
            options={
                'verbose_name': 'Pest affecting Crop',
                'unique_together': {('crop', 'pest')},
            },
        ),
    ]
