# Generated by Django 5.2.6 on 2025-12-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0011_remove_disease_affected_crops_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropdisease',
            old_name='specific_symptoms',
            new_name='specific_damage',
        ),
        migrations.RenameField(
            model_name='croppest',
            old_name='specific_symptoms',
            new_name='specific_damage',
        ),
        migrations.RemoveField(
            model_name='croppest',
            name='economic_threshold',
        ),
        migrations.AlterField(
            model_name='pest',
            name='description',
            field=models.TextField(help_text='General description and identification of the pest'),
        ),
    ]
