# Generated by Django 5.2.6 on 2025-12-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0012_rename_specific_symptoms_cropdisease_specific_damage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Nitrogen (N), Phosphorus (P)', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropNutrientDeficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiency_symptoms', models.TextField(help_text='Visual symptoms of this deficiency on the crop.')),
                ('symptom_image', models.ImageField(blank=True, help_text='Upload a picture of the deficiency symptoms', null=True, upload_to='nutrient_deficiencies/')),
                ('correction', models.TextField(help_text='Methods or fertilizers to correct this deficiency.')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_deficiencies', to='agrigeo.crop')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_deficiencies', to='agrigeo.nutrient')),
            ],
            options={
                'verbose_name': 'Crop Nutrient Deficiency',
                'verbose_name_plural': 'Crop Nutrient Deficiencies',
                'unique_together': {('crop', 'nutrient')},
            },
        ),
    ]
