# Generated by Django 5.2.6 on 2025-12-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrigeo', '0013_nutrient_cropnutrientdeficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmboundary',
            name='location',
        ),
        migrations.AlterField(
            model_name='farmboundary',
            name='area',
            field=models.FloatField(blank=True, help_text='Area in acres', null=True),
        ),
    ]
